import pandas as pd
import os

def combine_csv_to_excel():
    """
    Finds all CSV files in the current directory, reads each one, and saves it
    as a separate sheet in a single Excel file.
    """
    # List of CSV files generated by the awk script
    csv_files = [
        "hawk_test_start_end.csv",
        "testeng_test_times.csv",
        "sns_defib_analysis.csv",
        "commeng_test_time.csv",
        "instance_utilization_details.csv"
    ]
    
    output_excel_file = 'log_analysis_summary.xlsx'

    try:
        # Create a Pandas Excel writer using openpyxl as the engine.
        with pd.ExcelWriter(output_excel_file, engine='openpyxl') as writer:
            print(f"Creating Excel file: {output_excel_file}")

            # Loop through the list of CSV files
            for csv_file in csv_files:
                # Check if the CSV file exists before trying to read it
                if os.path.exists(csv_file):
                    try:
                        # Read the CSV file into a pandas DataFrame
                        df = pd.read_csv(csv_file)
                        
                        # Create a clean sheet name from the CSV filename
                        # (e.g., "hawk_test_start_end.csv" -> "hawk_test_start_end")
                        # Also, truncate if it's too long for Excel's sheet name limit (31 chars)
                        sheet_name = os.path.splitext(csv_file)[0][:31]
                        
                        # Write the DataFrame to a specific sheet in the Excel file
                        df.to_excel(writer, sheet_name=sheet_name, index=False)
                        
                        print(f"  - Added sheet '{sheet_name}' from '{csv_file}'")

                    except Exception as e:
                        print(f"  - Could not process {csv_file}. Error: {e}")
                else:
                    print(f"  - Skipping '{csv_file}' because it was not found.")
        
        print(f"\nSuccessfully combined CSV files into '{output_excel_file}'")

    except Exception as e:
        print(f"An error occurred while creating the Excel file: {e}")

if __name__ == "__main__":
    combine_csv_to_excel()

